### ISSUE TITLE
Fix misinformation in documentation

### ISSUE THREAD

**Issue by firasuke** [skarnet/lh-bootstrap#2]
Hey there, I was reading [this](https://github.com/skarnet/lh-bootstrap/blame/0a561c2947dda6222153bb8f32d35cff93eaf5af/doc/DEPENDENCIES-BUILD.md#L155), and I saw `xz` being mentioned as a faster decompressor compared to `gzip` which I don't think is true?

**Comment by skarnet** [comment]
Heh, it looks like you're right. Thanks, will fix.

**Comment by skarnet** [comment]
Done. I removed some obsolete mentions of util-linux as well. I don't really maintain that doc anymore, to be honest 😅
