### ISSUE TITLE
lastb does not work as /var/log/btmp does not exist

### ISSUE THREAD

**Issue by firasuke** [skarnet/lh-bootstrap#3]
I stumbled upon this issue when running `lastb`. It seems that `/var/log/wtmpd/btmp` isn't being created even though `utmps-wtmpd btmp` is being run.

What could be the issue?

**Comment by skarnet** [comment]
No history of failed logins, so no file is being created? Does `lastb` work if you touch an empty `/var/log/wtmpd/btmp`?

**Comment by firasuke** [comment]
> No history of failed logins, so no file is being created? Does `lastb` work if you touch an empty `/var/log/wtmpd/btmp`?

I tried several failed logins, and it appears that `btmp` isn't being created. If I do a `touch /var/log/wtmpd/btmp` then and fail a login attempt then `lastb` works just fine, so it appears an issue of `/var/log/wtmpd/btmp` not being created.

Same goes for `lastlog`, I had another service in the style of the `btmpd` service (also has `/var/log/wtmpd/lastlog` (with `/var/log/lastlog` being a symlink to it), and it wouldn't work until I do a `touch /var/log/wtmpd/lastlog`.

**Comment by skarnet** [comment]
I added empty wtmp and btmp files to the starting layout. It should help.

lastlog is something entirely different though, not provided by default in lh-bootstrap, so if you want it, keep manually adding it 😉

**Comment by firasuke** [comment]
I see. Thanks for the quick replies, much appreciated!

Closing..
